### ISSUE TITLE
some help plz

### ISSUE THREAD

**Issue by BallisticOK** [SharifPoetra/tokisaki#24]
this.eco = new Economy();
               ^

TypeError: Economy is not a constructor

**Comment by BallisticOK** [comment]
Found total 6 category.
Found total 5 command from admin.
Found total 15 command from economy.
internal/modules/cjs/loader.js:1080
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\ashfl\Downloads\tokisaki\node_modules\parse-ms\index.js
require() of ES modules is not supported.
require() of C:\Users\ashfl\Downloads\tokisaki\node_modules\parse-ms\index.js from C:\Users\ashfl\Downloads\tokisaki\src\commands\economy\dailies.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\ashfl\Downloads\tokisaki\node_modules\parse-ms\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\ashfl\Downloads\tokisaki\src\commands\economy\dailies.js:4:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'ERR_REQUIRE_ESM'
}
(node:6464) UnhandledPromiseRejectionWarning: Error [SHARDING_READY_DIED]: Shard 0's process exited before its Client became ready.
    at Shard.onDeath (C:\Users\ashfl\node_modules\discord.js\src\sharding\Shard.js:158:16)
    at Object.onceWrapper (events.js:422:26)
    at Shard.emit (events.js:315:20)
    at Shard._handleExit (C:\Users\ashfl\node_modules\discord.js\src\sharding\Shard.js:384:10)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
(node:6464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)

**Comment by Nostorian** [comment]
this code is dead shit

**Comment by SharifPoetra** [comment]
This project is outdated, I didn't recommend using it anymore. Consider waiting at my upcoming projects!
