### ISSUE TITLE
Error with canvas

### ISSUE THREAD

**Issue by LunaryUStyle** [SharifPoetra/tokisaki#9]
Hey ! So I tried the profile command, and when I start the bot, it tells me this :
```
Error: Cannot find module 'canvas'
Require stack:
- c:\Users\Ce Pc\Desktop\Bureau\Rin\node_modules\canvas-constructor\src\lib\util\util.js
- c:\Users\Ce Pc\Desktop\Bureau\Rin\node_modules\canvas-constructor\src\lib\canvas.js
- c:\Users\Ce Pc\Desktop\Bureau\Rin\node_modules\canvas-constructor\src\index.js
- c:\Users\Ce Pc\Desktop\Bureau\Rin\Commands\profile.js
- c:\Users\Ce Pc\Desktop\Bureau\Rin\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1014:15)
    at Function.Module._load (internal/modules/cjs/loader.js:884:27)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at c:\Users\Ce Pc\Desktop\Bureau\Rin\node_modules\canvas-constructor\src\lib\util\util.js:10:10
    at Object.<anonymous> (c:\Users\Ce Pc\Desktop\Bureau\Rin\node_modules\canvas-constructor\src\lib\util\util.js:12:3)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (c:\Users\Ce Pc\Desktop\Bureau\Rin\node_modules\canvas-constructor\src\lib\canvas.js:3:62)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
``` 
And I don't know how to fix it, canvas-constructor is installed and I tried to `npm i canvas`,
but this don't work. Help me please !

**Comment by LunaryUStyle** [comment]
@SharifPoetra Help please

**Comment by LunaryUStyle** [comment]
I installed GTK and node pre gyp and it still don't work...

**Comment by SharifPoetra** [comment]
There's nothing I can do about that, I suggest you to take a look at canvas [wiki](https://github.com/Automattic/node-canvas/wiki/_pages) for better information on installing it.

**Comment by LunaryUStyle** [comment]
I got it to work, but now i can't send the canvas @SharifPoetra

**Comment by SharifPoetra** [comment]
I'm sorry but did you properly read the [Lisence](https://github.com/SharifPoetra/tokisaki/blob/master/LICENSE)? There's mentioned that No Warranty Of Any Kind.
